### ISSUE TITLE
Ephemeral builder tars are missing base image layers

### ISSUE THREAD

**Issue by matejvasek** [buildpacks/pack#925]
When creating ephemeral builder the `pack` binary uses hack optimization when creating tar stream. The tar pushed to repo is missing some layers, the layers are however already present as they are downloaded in advance so it's still somehow working. But that is not a valid format. This causes issues for instance for `podman` which has more strict validation.

**Comment by matejvasek** [comment]
For more info https://github.com/containers/podman/issues/8132.

**Comment by matejvasek** [comment]
This will block https://github.com/buildpacks/pack/issues/564.

**Comment by jromero** [comment]
Hi @matejvasek, thanks for the report. If it's what I'm thinking about, yes we are using an optimization hack specific to the docker daemon implementation. @ekcasey was the mastermind IIRC. 

The "simple fix" as [mentioned](https://github.com/containers/podman/issues/8132#issuecomment-716807403) by @mtrmac is something we've recently contemplated but will take a bit longer to implement in the way we've previously discussed it. We can investigate a little further and determine smaller changes to resolve the issue in a shorter timeframe.

**Comment by ekcasey** [comment]
Yes this is a hack that we added to improve performance against the docker daemon. It is crucial that we keep this hack in place when using the docker daemon because the performance implications are enormous.

We could likely make the hack configurable in `imgutil` and toggle it on/off for docker/podman, but performance may suffer for pack+podman users.

**Comment by dfreilich** [comment]
@ekcasey You had run an experiment somewhere to see what those performance implications were, right? Any chance you could repost those?

**Comment by ekcasey** [comment]
@dfreilich We did this a looong time ago (sometime in 2018) so suffice it to say I don't have original comparison data handy, but we can do some back of the envelope math. The time saved is the time it takes to `docker save` and then `docker load` the base image.

For example, if I am creating an ephemeral builder with a single additional buildpack the "base image" is the original builder. It just took me **29.646s** to `docker save -o builder.tar paketobuildpacks/builder:full` and **26.103s** to `docker load -i builder.toml` so for this (admittedly larger) builder the hack is saving users close to **one minute** when for the command `pack build --builder paketobuildpacks/builder:full --buildpack <buildpack>`

**Comment by jromero** [comment]
@matejvasek,

@ekcasey started working on this but found a [separate issue](https://github.com/buildpacks/pack/issues/966), reported by @abitrolly, that looks like might stem from the podman vs docker implementation. Are you able to look at the possible cause for podman not providing platform information as detailed in https://github.com/buildpacks/pack/issues/966?

**Comment by matejvasek** [comment]
@jromero 
I'll look at it. I might be caused by missing implementation for /containers/{id}/archive endpoint. I recently implemented that https://github.com/containers/podman/pull/8126, but it's probably not released yet.

**Comment by matejvasek** [comment]
Also 2.1 and 2.2 doesn't contain this fix of mine: https://github.com/containers/podman/pull/8109. Could you please try build from master?

**Comment by matejvasek** [comment]
After pack update I can reproduce the issue #966 it on master. I just used older version of `pack` before.

**Comment by matejvasek** [comment]
Hmm the OS is empty string in response JSON. I'll try to fix that.

**Comment by matejvasek** [comment]
@jromero After some digging I found out it's been fixed here https://github.com/containers/podman/pull/8494. So `podman` master should work.

**Comment by jromero** [comment]
Hi @matejvasek, just trying to button up everything here. Given that https://github.com/buildpacks/lifecycle/pull/485 was released in lifecycle 0.10.0, this should be addresses when using a builder with a lifecycle version >= 0.10.0. I'm assuming it's all tied to https://github.com/buildpacks/pack/issues/966.

Please reopen if I'm mistaken.

**Comment by vlk-charles** [comment]
I don't know if it's still relevant to this issue but the hack can be made to work with Podman too. You just have to reference something in `manifest.json` instead of leaving the paths empty for layers. See https://github.com/containers/podman/issues/8132#issuecomment-921042467. This shouldn't break Docker compatibility.

**Comment by i-bs** [comment]
The problem came back:
```
$ skopeo copy -f oci docker-daemon:bellsoft/builder:glibc oci:/push_container_image_tmp/111
FATA[0001] determining manifest MIME type for docker-daemon:bellsoft/builder:glibc: Layer tarfile "blobs/sha256/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" used for two different DiffID values 
```
The image is built with pack v0.39.0-rc1
